version: "3"
services:
  app:
    container_name: photo-gallery
    restart: always
    build: .
    ports:
      - "3003:3003"
    links:
      - mongo
    # environment:
    #   MONGO_USERNAME: root
    #   MONGO_PASSWORD:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - "27017:27017"
